import G2AreaChart from './components/area';
import G2BarChart from './components/bar';
import G2BulletChart from './components/bullet';
import G2ColumnChart from "./components/column";
import G2DualAxesChart from "./components/dual-axes";
import G2FunnelChart from "./components/funnel";
import G2GaugeChart from "./components/gauge";
import G2LineChart from "./components/line";
import G2LiquidChart from "./components/liquid";
import G2PieChart from "./components/pie";
import G2RadarChart from "./components/radar";
import G2ScatterChart from "./components/scatter";
import { G2 } from '@antv/g2plot';
export { G2AreaChart, G2BarChart, G2BulletChart, G2ColumnChart, G2DualAxesChart, G2FunnelChart, G2GaugeChart, G2LiquidChart, G2LineChart, G2PieChart, G2RadarChart, G2ScatterChart, G2 };
declare const _default: {
    G2AreaChart: import("react").ForwardRefExoticComponent<import("./components/area").AreaConfig & import("react").RefAttributes<unknown>>;
    G2BarChart: import("react").ForwardRefExoticComponent<import("./components/bar").BarConfig & import("react").RefAttributes<unknown>>;
    G2BulletChart: import("react").ForwardRefExoticComponent<import("./components/bullet").BulletConfig & import("react").RefAttributes<unknown>>;
    G2ColumnChart: import("react").ForwardRefExoticComponent<import("./components/column").ColumnConfig & import("react").RefAttributes<unknown>>;
    G2DualAxesChart: import("react").ForwardRefExoticComponent<import("./components/dual-axes").DualAxesConfig & import("react").RefAttributes<unknown>>;
    G2FunnelChart: import("react").ForwardRefExoticComponent<import("./components/funnel").FunnelConfig & import("react").RefAttributes<unknown>>;
    G2GaugeChart: import("react").ForwardRefExoticComponent<import("./components/gauge").GaugeConfig & import("react").RefAttributes<unknown>>;
    G2LiquidChart: import("react").ForwardRefExoticComponent<import("./components/liquid").LiquidConfig & import("react").RefAttributes<unknown>>;
    G2LineChart: import("react").ForwardRefExoticComponent<import("./components/line").LineConfig & import("react").RefAttributes<unknown>>;
    G2PieChart: import("react").ForwardRefExoticComponent<import("./components/pie").PieConfig & import("react").RefAttributes<unknown>>;
    G2RadarChart: import("react").ForwardRefExoticComponent<import("./components/radar").RadarConfig & import("react").RefAttributes<unknown>>;
    G2ScatterChart: import("react").ForwardRefExoticComponent<import("./components/scatter").ScatterConfig & import("react").RefAttributes<unknown>>;
    G2: typeof G2;
};
export default _default;
export * from './interface';
